# Generated by Django 5.0.6 on 2026-03-30 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_disabilities_patient_has_pending_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_type', models.CharField(choices=[('inpatient', 'Inpatient Admission'), ('outpatient', 'Outpatient Visit'), ('emergency', 'Emergency'), ('day_case', 'Day Case / Day Surgery'), ('review', 'Follow-up Review')], default='outpatient', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active / Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('outpatient', 'Outpatient — Completed')], default='outpatient', max_length=20)),
                ('encounter_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Visit / Admission')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Date of Discharge')),
                ('ward_admitted', models.CharField(blank=True, choices=[('general_male', 'General Ward (Male)'), ('general_female', 'General Ward (Female)'), ('paediatric', 'Paediatric Ward'), ('maternity', 'Maternity Ward'), ('icu', 'ICU / Critical Care'), ('surgical', 'Surgical Ward'), ('medical', 'Medical Ward'), ('private', 'Private Ward'), ('semi_private', 'Semi-Private Ward'), ('emergency', 'Emergency Ward'), ('other', 'Other')], max_length=30)),
                ('bed_number', models.CharField(blank=True, max_length=20)),
                ('referring_doctor', models.CharField(blank=True, max_length=200, verbose_name='Referring Doctor / Facility')),
                ('consultant_name_text', models.CharField(blank=True, max_length=200, verbose_name='Consultant (if not in system)')),
                ('billing_code', models.CharField(blank=True, max_length=100, verbose_name='Billing / CPT Code')),
                ('presenting_complaint', models.TextField(blank=True, verbose_name='Presenting Complaint / Reason for Visit')),
                ('history_of_illness', models.TextField(blank=True, verbose_name='History of Presenting Illness')),
                ('examination_findings', models.TextField(blank=True, verbose_name='Examination Findings')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Treatment Plan / Management')),
                ('discharge_summary', models.TextField(blank=True)),
                ('doctors_report', models.TextField(blank=True, verbose_name="Doctor's Report / Clinical Notes")),
                ('approved_for_patient', models.BooleanField(default=False, verbose_name='Approved for Patient Portal')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_encounters', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_as_consultant', to=settings.AUTH_USER_MODEL, verbose_name='Consultant / Doctor in Charge')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Encounter',
                'verbose_name_plural': 'Patient Encounters',
                'ordering': ['-encounter_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(default=django.utils.timezone.now)),
                ('operation_type', models.CharField(choices=[('elective', 'Elective Surgery'), ('emergency', 'Emergency Surgery'), ('minor', 'Minor Procedure'), ('major', 'Major Surgery'), ('laparoscopic', 'Laparoscopic / Minimally Invasive'), ('diagnostic', 'Diagnostic Procedure'), ('therapeutic', 'Therapeutic Procedure'), ('other', 'Other')], default='minor', max_length=20)),
                ('operation_name', models.CharField(max_length=300, verbose_name='Name / Title of Operation')),
                ('operation_code', models.CharField(blank=True, max_length=50, verbose_name='Operation / CPT Code')),
                ('anaesthesia_type', models.CharField(blank=True, max_length=100, verbose_name='Anaesthesia Type')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('outcome', models.CharField(choices=[('successful', 'Successful'), ('complicated', 'Complicated'), ('failed', 'Failed / Abandoned'), ('pending', 'Pending / Scheduled')], default='successful', max_length=20)),
                ('surgeon_text', models.CharField(blank=True, max_length=200, verbose_name='Lead Surgeon (if not in system)')),
                ('notes', models.TextField(blank=True, verbose_name='Operation Notes')),
                ('doctors_remark', models.TextField(blank=True, verbose_name="Doctor's Post-Op Remark")),
                ('complications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_performed', to=settings.AUTH_USER_MODEL, verbose_name='Lead Surgeon')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='clinical_records.patientencounter')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'ordering': ['-operation_date'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis_code', models.CharField(blank=True, help_text='e.g. J18.9 for Pneumonia, I10 for Hypertension', max_length=20, verbose_name='ICD-10 Code')),
                ('diagnosis_name', models.CharField(max_length=300, verbose_name='Diagnosis Name / Description')),
                ('diagnosis_type', models.CharField(choices=[('primary', 'Primary Diagnosis'), ('secondary', 'Secondary / Comorbidity'), ('differential', 'Differential Diagnosis'), ('provisional', 'Provisional / Working Diagnosis'), ('final', 'Final Diagnosis'), ('discharge', 'Discharge Diagnosis')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name="Diagnosis Notes / Doctor's Remarks")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical_records.patientencounter')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-diagnosis_date'],
            },
        ),
    ]
