# Generated by Django 5.0.6 on 2026-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_medicalrecord_is_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_downloadable',
            field=models.BooleanField(default=False, help_text='If ticked, authorised users can download the attached file. Admin and the uploading doctor can always download regardless of this setting.', verbose_name='Allow file download'),
        ),
    ]
