# Generated by Django 5.0.6 on 2026-03-31 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyroster',
            name='notes',
            field=models.TextField(blank=True, help_text='General instructions for this roster period'),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='title',
            field=models.CharField(help_text='e.g. Week 3 July 2025 — Night Shift Schedule', max_length=200),
        ),
        migrations.AlterField(
            model_name='materialused',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Item / Material Name'),
        ),
        migrations.AlterField(
            model_name='materialused',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unit (pieces/ml/L/boxes)'),
        ),
        migrations.AlterField(
            model_name='medicationadminrecord',
            name='reason_withheld',
            field=models.TextField(blank=True, verbose_name='Reason if Withheld/Refused/Missed'),
        ),
        migrations.AlterField(
            model_name='medicationadminrecord',
            name='route',
            field=models.CharField(blank=True, max_length=50, verbose_name='Route (oral/IV/IM/SC)'),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='content',
            field=models.TextField(verbose_name='Note Content'),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Flagged for doctor review'),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='was_voice',
            field=models.BooleanField(default=False, verbose_name='Transcribed from voice'),
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='nurse',
            field=models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='ward',
            field=models.CharField(blank=True, choices=[('general_male', 'General Ward (Male)'), ('general_female', 'General Ward (Female)'), ('paediatric', 'Paediatric Ward'), ('maternity', 'Maternity Ward'), ('icu', 'ICU / Critical Care'), ('surgical', 'Surgical Ward'), ('medical', 'Medical Ward'), ('emergency', 'Emergency Ward'), ('all', 'All Wards')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='general_ward_notes',
            field=models.TextField(blank=True, verbose_name='General Ward Notes'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='handover_summary',
            field=models.TextField(blank=True, help_text='Summary of ward status to hand over to the next shift', verbose_name='Handover Summary'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='incidents',
            field=models.TextField(blank=True, verbose_name='Incidents / Events This Shift'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='outstanding_tasks',
            field=models.TextField(blank=True, verbose_name='Outstanding Tasks / Pending Actions'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='ward',
            field=models.CharField(choices=[('general_male', 'General Ward (Male)'), ('general_female', 'General Ward (Female)'), ('paediatric', 'Paediatric Ward'), ('maternity', 'Maternity Ward'), ('icu', 'ICU / Critical Care'), ('surgical', 'Surgical Ward'), ('medical', 'Medical Ward'), ('emergency', 'Emergency Ward'), ('all', 'All Wards')], default='general_female', max_length=20),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Blood Glucose (mmol/L)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='blood_pressure_dia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Diastolic BP (mmHg)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='blood_pressure_sys',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Systolic BP (mmHg)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Vitals Notes / Observations'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='oxygen_saturation',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='SpO2 (%)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='pain_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pain Score (0–10)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='pulse_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulse Rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Respiratory Rate (breaths/min)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='urine_output_ml',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Urine Output (ml)'),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
    ]
