# Generated by Django 5.0.6 on 2026-03-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disabilities',
            field=models.TextField(blank=True, verbose_name='Disabilities / Special Needs'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_pending_fields',
            field=models.BooleanField(default=False, help_text='True if any fields contain PENDING dummy data from import'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='HMO Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hometown',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hometown / Village'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='lga',
            field=models.CharField(blank=True, max_length=100, verbose_name='Local Government Area (LGA)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nhis_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='NHIS Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nok_alt_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Next of Kin Alt. Phone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nok_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Next of Kin Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nok_occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Next of Kin Occupation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pending_field_list',
            field=models.TextField(blank=True, help_text='Comma-separated list of fields that have PENDING values'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Preferred Name / Nickname'),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Language'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Current Ward (if admitted)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, verbose_name='Current Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Prefer not to say')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='legacy_hospital_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Old/Previous Hospital Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, default='Nigerian', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nok_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Next of Kin Full Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nok_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('child', 'Child'), ('guardian', 'Guardian'), ('friend', 'Friend'), ('other', 'Other')], max_length=20, verbose_name='Relationship to Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('traditional', 'Traditional'), ('other', 'Other'), ('none', 'None')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
